services:
  microsoft-rewards-script:
    build: .
    container_name: microsoft-rewards-script
    restart: on-failure
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
    volumes:
      ### Replace "/path/to/" with the actual path to where you want to save the files on your local machine.
      - /home/tools/Microsoft-Rewards-Script-1.5/savedist/accounts.json:/usr/src/microsoft-rewards-script/dist/accounts.json
      - /home/tools/Microsoft-Rewards-Script-1.5/savedist/config.json:/usr/src/microsoft-rewards-script/dist/config.json 
      # - /home/tools/Microsoft-Rewards-Script/savedist/browser/sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions # Optional, saves your login session
    environment:
      - NODE_ENV=production
      - CRON_SCHEDULE=0 7,15,20 * * * # Customize your schedule, use crontab.guru for formatting
      - RUN_ON_START=true # Runs the script on container startup
      - TZ=Asia/Shanghai # Set your timezone for proper scheduling

networks:
  mynetwork:
    external: true
